version: "3.4"

services:
  http:
     image: nginx:alpine
     networks:
       - reverse_proxy
     volumes:
       - repos:/usr/share/nginx/html
       - ./default.conf:/etc/nginx/conf.d/default.conf:ro
     environment:
       VIRTUAL_HOST: repos.glud.org
       LETSENCRYPT_MAIL: sytabaresa@gmail.com
       HTTPS_METHOD: noredirect
     deploy:
       placement:
         constraints:
           - node.hostname == glud.udistrital.edu.co
networks:
  reverse_proxy:
    external: true

volumes:
  repos:
