version: "3.1"

services:
  grafana:
    image: grafana/grafana:latest
    networks:
      - reverse_proxy
      - backend
      - metrics
    volumes:
      - data:/var/lib/grafana
    env_file:
      - ./grafana.env.priv
    environment:
      GF_SERVER_ROOT_URL: http://grafana.glud.org
      GF_USERS_ALLOW_ORG_CREATE: "true"

      VIRTUAL_HOST: grafana.glud.org
      LETSENCRYPT_HOST: grafana.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s       
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]
networks:
  backend:
  reverse_proxy:
    external: true
  metrics:
    external: true
volumes:
  data:
