version: '3.1'

services:
  term:
    image: glud/wetty:latest
    hostname: glud.org
    volumes:
      - glud:/home/glud/
    networks:
      - reverse_proxy
    environment:
      #WETTY_USER: glud
      #WETTY_PASSWORD: nomelase2
      WETTY_USERS_FILE: /run/secrets/users
      ## For reverse proxy
      VIRTUAL_HOST: terminal.glud.org
      LETSENCRYPT_HOST: terminal.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    secrets:
      - users
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]

volumes:
  glud:

networks:
  reverse_proxy:
    external: true

secrets:
  users:
    file: ./users.priv
