version: "3.1"

services:
  moodle-cursos:
    image: glud/moodle:latest
    #ports:
    #  - 80:80
    networks:
      - frontend
      - backend
      - reverse_proxy
    depends_on:
      - db
    volumes:
      - moodledata:/var/moodledata
    secrets:
      - db_password
    environment:  
      MOODLE_URL: https://cursos.glud.org
      DB_TYPE: pgsql #or mariadb
      DB_TCP_ADDR: db
      DB_ENV_DATABASE: moodle
      DB_ENV_USER: moodle
      DB_ENV_PASSWORD_FILE: /run/secrets/db_password
      SSL_ENABLED: "true"
      # For reverse proxy
      VIRTUAL_HOST: cursos.glud.org 
      LETSENCRYPT_HOST: cursos.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

## MariaDB configuration:
#  db:
#    image: mariadb
#    networks:
#      - backend
#    #ports:
#    #  - 3306:3306
#    volumes:
#      - dbdata:/var/lib/mysql
#    secrets:
#      - db_password
#    environment:
#      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
#      - MYSQL_USER=moodle
#      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
#      - MYSQL_DATABASE=moodle
#    deploy:
#      restart_policy:
#        replicas: 1
#        condition: on-failure
#        delay: 5s
        
## PostgreSQL configuration        
  db:
    image: postgres:9
    networks:
      - backend
    #ports:
    #  - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: moodle
      POSTGRES_DB: moodle
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

#  adminer:
#    image: adminer
#    #ports:
#    #  - 8080:80
#    networks:
#      - backend
#    depends_on:
#      - db

networks:
  backend:
  frontend:
  reverse_proxy:
    external: true

volumes:
  dbdata:
  moodledata:

secrets:
  db_password:
    file: ./db_password.priv
