version: "3"

services:
  nodered:
    image: nodered/node-red-docker
    volumes: 
     - data:/data
    networks:
     - reverse_proxy
     - intralora
    environment:
      VIRTUAL_HOST: nodered.glud.org
      LETSENCRYPT_HOST: nodered.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s       
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]

#      FLOW:  test.json
#      NODE_OPTIONS: "--max_old_space_size=128"




networks:
  intralora:
     external: true
  reverse_proxy:
     external: true    

volumes:
  data:

