version: "3.1"

services:
  back:
    image: glud/slud-backend:latest
    networks:
      - backend
      - reverse_proxy
    environment:
      SECRET_KEY_FILE: "./secret_key"
      ADMIN_USER: root
      ADMIN_EMAIL: "sytabaresa@gmail.com"
      ADMIN_PASSWORD_FILE: "./admin_key"
      PUBLIC_HOST: sludapi.glud.org
      VIRTUAL_HOST: sludapi.glud.org
      LETSENCRYPT_HOST: sludapi.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    volumes:
      - ./django.priv:/usr/src/app/secret_key
      - ./admin.priv:/usr/src/app/admin_key
      - data:/usr/src/app/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]

  front:
    image: glud/slud-frontend:latest
    networks:
      - backend
      - reverse_proxy
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: semana.glud.org,slud.glud.org
      LETSENCRYPT_HOST: semana.glud.org,slud.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]

volumes:
  data:

networks:
  backend:
  reverse_proxy:
    external: true
        
