version: "3.1"

services:
  back:
    image: glud/slud-backend:latest
    networks:
      - backend
    environment:
      API_SECRET: 123

  front:
    image: glud/slud-frontend:latest
    networks:
      - backend
      - reverse_proxy
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: semana.glud.org
      LETSENCRYPT_HOST: semana.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com


networks:
  backend:
  reverse_proxy:
    external: true
        
