version: '3.1'

services:
  webpage:
    image: ghost:alpine
    #command: npm --production start
    networks:
      - backend
      - reverse_proxy
    depends_on:
      - db
    volumes:
      - data:/var/lib/ghost/content
      - ./config-private.production.json:/var/lib/ghost/config.production.json:ro
    environment:
      NODE_ENV:
      VIRTUAL_HOST: blog.glud.org
      LETSENCRYPT_HOST: blog.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    secrets:
      - db_password
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s       
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]

  db:
    image: mariadb
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=ghost
    secrets:
      - db_password
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s       
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]


networks:
  backend:
  reverse_proxy:
    external: true
 
volumes:
  dbdata:
  data:

secrets:
  db_password:
    file: ./db_password.priv
