version: '3.1'

services:
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: taiga
      POSTGRES_DB: taiga
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend
    secrets:
      - db_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]

  taigaback:
    image: glud/taiga-back:latest
    hostname: taigaback.glud.org
    environment:
      SECRET_KEY_FILE: /run/secrets/secret_key
      EMAIL_USE_TLS: 'True'
      EMAIL_HOST: smtp.mailgun.org
      EMAIL_PORT: 587
      EMAIL_HOST_USER: taiga@glud.org
      EMAIL_HOST_PASSWORD_FILE: /run/secrets/email_password
      DEFAULT_FROM_EMAIL: info@taiga.glud.org
      FRONT_SCHEME: https
      FRONT_DOMAIN: taiga.glud.org
      POSTGRES_USER: taiga
      POSTGRES_HOST: db
      POSTGRES_DB_NAME: taiga
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      GITHUB_API_CLIENT_ID: f7de0ec469e65e42db28
      GITHUB_API_CLIENT_SECRET_FILE: /run/secrets/github_secret_key
      ## For reverse proxy
      VIRTUAL_HOST: taigaback.glud.org
      LETSENCRYPT_HOST: taigaback.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    volumes:
      - media:/usr/local/taiga/media     
      - static:/usr/local/taiga/static
      - logs:/usr/local/taiga/logs
    networks:
      - backend
      - frontend
      - reverse_proxy
    secrets:
      - db_password 
      - email_password
      - secret_key
      - github_secret_key
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]

  taigafront:
    image: glud/taiga-front:latest
    hostname: taiga.glud.org
    volumes:
      - media:/usr/local/taiga/media   
      - static:/usr/local/taiga/static
      - logs:/usr/local/taiga/logs
    environment:
      #API: taigaback.glud.org
      TAIGABACK_PORT_8000_TCP_ADDR: taigaback
      TAIGA_LANG: es
      GITHUB_API_CLIENT_ID: f7de0ec469e65e42db28
      ## For reverse proxy
      VIRTUAL_HOST: taiga.glud.org,taiga.nsupdate.info
      LETSENCRYPT_HOST: taiga.glud.org
      LETSENCRYPT_EMAIL: sytabaresa@gmail.com
    networks:
      - frontend
      - reverse_proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]

networks:
  backend:
  frontend:
  reverse_proxy:
    external: true
   
volumes:
  media:
  dbdata:
  static:
  logs:

secrets:
  db_password:
    file: ./db_password.priv
  email_password:
    file: ./email_password.priv
  secret_key:
    file: ./secret_key.priv
  github_secret_key:
    file: ./github_secret_key.priv
